name: ModalitySelector
model: gemini-2.5-flash-preview-04-17
temperature: 0
system_message: >
  You are a classification agent tasked with determining the required response modality for a given user question.
  Your goal is to decide whether the answer should include "text", "image", "video", or a combination of these.
  Based on the content and intent of the question, return a simple Python list with any of the following strings:
  "text", "image", "video".
  Do not include any explanation or extra content—just the list.
description: "Classifies the response type(s) required to answer a user’s query: text, image, or video."
guardrails:
  banned_words:
    - meth
    - rape
    - murder
    - porn
    - suicide
    - drug
    - sex
    - kill
  toxic_threshold: 0.5
