import logging
from typing import Any, List

from agents.base_agent import BaseAgent
from agno.tools.googlesearch import GoogleSearchTool
from omegaconf import DictConfig


class TextAgent(BaseAgent):
    def __init__(
        self,
        cfg: DictConfig,
        logger: logging.Logger,
        llm,
        tools: List[Any] = [GoogleSearchTool()],
    ) -> None:
        super().__init__(cfg=cfg.text_agent, logger=logger, llm=llm, tools=tools)

    def run(self, query: str) -> List[str]:
        """
        Run the TextAgent to process the given query.

        Args:
            query (str): The input query to process.

        Returns:
            List[str]: A list of responses generated by the agent.
        """
        self.logger.info(f"Running TextAgent with query: {query}.")
        response = self.llm.generate(query, tools=self.tools)
        self.logger.info(f"TextAgent response: {response}")
        return [response]
